(async()=>{const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
  $('.menu-toggle').addEventListener('click',e=>{const n=$('#site-nav'),open=n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});$$('#site-nav a').forEach(a=>a.addEventListener('click',()=>$('#site-nav').classList.remove('open')));$('#year').textContent=new Date().getFullYear();
  try{const d=await fetch('content/site.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()});
    $('#hero-intro').textContent=d.heroIntro;$('#about-lead').textContent=d.aboutLead;$('#about-detail').textContent=d.aboutDetail;$('#academic-copy').textContent=d.academicCopy;
    if(d.portraitImage){const portraitUrl=assetUrl(d.portraitImage);$('#doctor-portrait').src=portraitUrl;$('#doctor-portrait').alt=d.portraitAlt||`Portrait of ${d.doctorName}`;$('#social-image').content=portraitUrl}
    $$('[data-hours]').forEach(e=>e.textContent=d.consultationHours);$$('[data-booking]').forEach(e=>e.textContent=d.appointmentMethods);$$('[data-registration]').forEach(e=>e.textContent=d.registrationNumber);
    $$('[data-primary-phone]').forEach(e=>e.textContent=d.primaryPhone);$$('[data-location]').forEach(e=>e.textContent=d.location);$$('[data-email]').forEach(e=>e.textContent=d.email);$$('[data-phone]').forEach(e=>e.href=`tel:${d.primaryPhone.replace(/\D/g,'')}`);$$('[data-email-link]').forEach(e=>e.href=`mailto:${d.email}`);$$('[data-whatsapp]').forEach(e=>e.href=`https://wa.me/${d.whatsappNumber}?text=${encodeURIComponent('Hello Dr. Patil, I would like to enquire about an appointment.')}`);
    $('#memberships').innerHTML=d.memberships.map(x=>`<span>${safe(x)}</span>`).join('');$('#services').innerHTML=d.services.map(s=>`<article class="service-card"><span class="service-icon">${safe(s.number)}</span><h3>${safe(s.title)}</h3><p>${safe(s.description)}</p></article>`).join('');$('#experience').innerHTML=d.experience.map(x=>`<article class="timeline-item"><time>${safe(x.period)}</time><h3>${safe(x.role)}</h3><p>${safe(x.institution)}</p></article>`).join('');
    $('#doctor-schema').textContent=JSON.stringify({'@context':'https://schema.org','@type':'Physician',name:d.doctorName,description:d.roleSummary||d.qualification,email:d.email,telephone:d.primaryPhone,address:{'@type':'PostalAddress',addressLocality:'Solapur',addressRegion:'Maharashtra',addressCountry:'IN'},medicalSpecialty:'Orthopedic',openingHours:'Mo-Sa 09:00-20:00'});
  }catch(e){console.warn('Editable site content could not be loaded.',e)}
  function assetUrl(v){return /^https?:\/\//i.test(v)?v:new URL(String(v).replace(/^\/+/,''),document.baseURI).href}
  function safe(v){const n=document.createElement('span');n.textContent=String(v);return n.innerHTML}
})();
